all:

	g++ -o client-phase1 client-phase1_keer.cpp -pthread -lstdc++fs 
	#g++ -o client-phase2 client-phase1.cpp -pthread -lstdc++fs 
	#g++ -o client-phase3 client-phase1.cpp -pthread -lstdc++fs 
	#g++ -o client-phase4 client-phase1.cpp -pthread -lstdc++fs 
	#g++ -o client-phase5 client-phase1.cpp -pthread -lstdc++fs 

clean:
	rm  client-phase1 client-phase2 client-phase3 client-phase4 client-phase5		
